<?/*
[global]
sitename=Multicounter Application
page_renderer=AjaxPageRenderer
translator=EnglishTranslator
app_class=MulticounterApplication
debugview=false
templates=enabled
[server]
serverhost=localhost
basename=
baseuser=
basepass=
basedir=
appdir=MyInstances
pwbdir=../../
site_url=
pwb_url=../../
db_driver=MySQLdb
baseprefix=
peardir=
*/?>