<?/*
[global]
sitename=Wiki Application
page_renderer=AjaxPageRenderer
translator=EnglishTranslator
debugview=false
templates=enabled
[server]
serverhost=localhost
basename=
baseuser=
basepass=
basedir=
appdir=MyInstances
pwbdir=../../
app_class=WikiApp
site_url=
pwb_url=../../
db_driver=MySQLdb
baseprefix=
peardir=
*/?>