<?/*
[global]
sitename=Wiki Application
page_renderer=AjaxPageRenderer
translator=EnglishTranslator
[server]
serverhost=localhost
basename=
baseuser=
basepass=
basedir=
appdir=MyInstances
pwbdir=../../
app_class=WikiApp
site_url=
pwb_url=../../
DBObject=MySQLdb
baseprefix=
peardir=
*/?>