<?/*
[global]
sitename=Blog Application
page_renderer=AjaxPageRenderer
page_renderer=StandardPageRenderer
translator=EnglishTranslator
app_class=ExampleBlogApplication
compile=
templates=enabled
[server]
serverhost=localhost
basename=database.sql
baseuser=
basepass=
basedir=
appdir=MyInstances
pwbdir=../../
site_url=
pwb_url=../../
db_driver=SQLiteDriver
baseprefix=
peardir=
*/?>
