<?php

require_once 'PWBObject.class.php';
require_once 'actions/NewActionDispatcher.class.php';
require_once 'Application.class.php';
require_once 'ApplicationLauncher.class.php';
require_once 'Component.class.php';
require_once 'ComponentHolder.class.php';
require_once 'ChildCallbackHandler.class.php';
require_once 'FunctionObject.class.php';
require_once 'components/meta/FieldsEmbeddingVisitor.class.php';
require_once 'components/meta/CollectionDisplayer.class.php';
require_once 'components/meta/ObjectEditor.class.php';
require_once 'components/meta/CollectionEditor.class.php';
require_once 'components/meta/ObjectDisplayer.class.php';
require_once 'components/BaseComponents/XML/XMLTextNode.class.php';
require_once 'components/BaseComponents/XML/XMLNode.class.php';
require_once 'components/BaseComponents/XML/NullView.class.php';
require_once 'components/BaseComponents/XML/DOMXMLNode.class.php';
require_once 'components/BaseComponents/XML/XMLModification.class.php';
require_once 'components/BaseComponents/XML/PageRenderer.class.php';
require_once 'components/BaseComponents/XML/XMLNodeModificationsTracker.class.php';
require_once 'components/BaseComponents/Text.class.php';
require_once 'components/BaseComponents/FormComponent.class.php';
require_once 'components/BaseComponents/CompositeFormComponent.class.php';
require_once 'components/BaseComponents/Input.class.php';
require_once 'components/BaseComponents/ActionLink.class.php';
require_once 'components/BaseComponents/Password.class.php';
require_once 'components/BaseComponents/Filename.class.php';
require_once 'components/BaseComponents/Label.class.php';
require_once 'components/BaseComponents/TextAreaComponent.class.php';
require_once 'components/BaseComponents/RadioButton.class.php';
require_once 'components/BaseComponents/CheckBox.class.php';
require_once 'components/NotificationDialog.class.php';
require_once 'components/QuestionDialog.class.php';
require_once 'components/Authenticator.class.php';
require_once 'components/PermissionsChecker.class.php';
require_once 'components/PromptDialog.class.php';
?>
