<?/*
[global]
sitename=Broadcast Application
page_renderer=AjaxPageRenderer
translator=EnglishTranslator
app_class=BroadcastApplication
debugview=false
templates=enabled
[server]
serverhost=localhost
basename=
baseuser=
basepass=
basedir=
appdir=MyInstances
pwbdir=../../
site_url=
pwb_url=../../
DBObject=MySQLdb
baseprefix=
peardir=
*/?>