<?/*
[global]
sitename=Broadcast Application
page_renderer=AjaxPageRenderer
translator=EnglishTranslator
app_class=BroadcastApplication
compile=
[server]
serverhost=localhost
basename=
baseuser=
basepass=
basedir=
appdir=MyInstances
pwbdir=../../
site_url=
pwb_url=../../
db_driver=MySQLdb
baseprefix=
peardir=
*/?>